[package]
name = "heos-lib"
version = "0.1.0"
authors = [
    "Christoph Kappel <christoph@unexist.dev>"
]
license-file = "LICENSE"
homepage = "https://unexist.dev"
repository = "https://hg.unexist.dev/heos-dial"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
const_format = "0.2.33"
async-stream = "0.3.6"
tokio = { version = "1.40.0", features = ["tokio-macros", "macros", "rt", "rt-multi-thread"] }
futures-util = "0.3.31"
