[package]
name = "heos-lib"
version = "0.1.0"
authors = [
    "Christoph Kappel <christoph@unexist.dev>"
]
license-file = "LICENSE"
homepage = "https://unexist.dev"
repository = "https://hg.unexist.dev/heos-dial"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
const_format = "0.2.33"
async-stream = "0.3.6"
tokio = { version = "1.41.0", features = ["net", "macros", "rt", "rt-multi-thread", "io-util"] }
futures-util = "0.3.31"
url = "2.5.3"
jsonpath-rust = "0.7.3"
serde_json = "1.0.133"
