version: '3'

tasks:
  test:
    cmds:
      - cargo test -- --nocapture

  test-*:
    vars:
      MOD: '{{index .MATCH 0}}'
    cmds:
      - cargo test heos_{{.MOD}}_test {{.CAPTURE}}

  cap-*:
    vars:
      MOD: '{{index .MATCH 0}}'
    cmds:
      - cargo test heos_{{.MOD}}_test -- --nocapture
