version: '3'

tasks:
  test:
    cmds:
      - cargo test -- --nocapture

  test-*:
    vars:
      MOD: '_{{index .MATCH 0}}'
    cmds:
      - cargo test heos{{.MOD}}_test

  cap-*:
    vars:
      MOD: '_{{index .MATCH 0}}'
    cmds:
      - cargo test heos{{.MOD}}_test -- --nocapture
