version: '3'
env:
  TEST_DEVICE_NAME: '{{.TEST_DEVICE_NAME | default "Studio1"}}'
  TEST_DEVICE_IP: '{{.TEST_DEVICE_IP | default "10.0.8.24"}}'
  TEST_GROUP_NAME: '{{.TEST_GROUP_NAME | default "All"}}'

tasks:
  test:
    cmds:
      - cargo test -- --nocapture

  cap:
    cmds:
      - cargo test

  test-async:
    cmds:
      - cargo test -- --include-ignored

  test-*:
    vars:
      MOD: '_{{index .MATCH 0}}'
    cmds:
      - cargo test heos{{.MOD}}_test -- --include-ignored

  cap-*:
    vars:
      MOD: '_{{index .MATCH 0}}'
    cmds:
      - cargo test heos{{.MOD}}_test -- --nocapture --include-ignored

  clean:
    cmds:
      - cargo clean
