name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  TEST_DEVICE_NAME: "Studio1"
  TEST_DEVICE_IP: "10.0.8.24"
  TEST_GROUP_NAME: "Almost"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd heos-lib && cargo build --verbose
    - name: Run tests
      run: cd heos-lib && cargo test --verbose
